# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(max_length=1)),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('identificacion', models.CharField(max_length=64)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email_personal', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
