# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ter_tipo', models.CharField(max_length=1)),
                ('ter_tipodoc', models.CharField(max_length=2)),
                ('ter_ident', models.CharField(max_length=64)),
                ('ter_nom', models.CharField(max_length=255)),
                ('ter_ap1', models.CharField(blank=True, max_length=255, null=True)),
                ('ter_ap2', models.CharField(blank=True, max_length=255, null=True)),
                ('ter_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ter_email', models.CharField(blank=True, max_length=20, null=True)),
                ('x_sync_corr1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
